"""Tests for the Plan-and-Execute pipeline (`src/agent/planner.py`).

Covers:
- complexity heuristic (`should_use_plan_and_execute`)
- free-tier clamp (`clamp_for_free_tier`)
- planner output validation (`_validate_outline`)
- executor sanitization (`_sanitize_executor_sessions`)
- assembly + final athlete-constraint validation
- end-to-end happy path with mocked LLM
- fallback on invalid planner JSON
- fallback on executor failure
- save_plan integration: free tier never triggers, Pro long plan triggers
"""

from __future__ import annotations

import json
from datetime import date, timedelta
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest

from src.agent import planner as planner_mod
from src.agent.planner import (
    PlannerResult,
    clamp_for_free_tier,
    generate_training_plan,
    should_use_plan_and_execute,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_profile(
    *,
    max_session_minutes: int = 90,
    training_days_per_week: int = 5,
    sports: list[str] | None = None,
    available_sports: list[str] | None = None,
    tier: str | None = None,
) -> dict:
    sports = sports or ["running"]
    return {
        "name": "Test",
        "sports": sports,
        "tier": tier,
        "goal": {"event": "Berlin Marathon", "target_date": "2026-09-27"},
        "fitness": {"estimated_vo2max": 55, "threshold_pace_min_km": 4.0},
        "constraints": {
            "max_session_minutes": max_session_minutes,
            "training_days_per_week": training_days_per_week,
            "available_sports": available_sports or sports,
        },
    }


def _next_monday() -> date:
    today = date.today()
    delta = (7 - today.weekday()) % 7
    return today + timedelta(days=delta or 7)


def _make_outline_payload(
    *,
    duration_weeks: int = 4,
    start_date: str | None = None,
    training_days_per_week: int = 5,
) -> dict:
    """Build a valid planner JSON payload for `duration_weeks` weeks."""
    start_date = start_date or _next_monday().isoformat()
    weekdays = ["monday", "tuesday", "wednesday", "thursday",
                "friday", "saturday", "sunday"]
    template_values = ["easy", "quality", "easy", "long", "rest",
                       "long_or_quality", "rest"]
    # Adjust template so non-rest count matches training_days_per_week.
    template_values = ["rest"] * 7
    pick = ["tuesday", "thursday", "saturday", "monday", "wednesday",
            "sunday", "friday"]
    for d in pick[:training_days_per_week]:
        template_values[weekdays.index(d)] = (
            "quality" if d == "tuesday"
            else "long" if d == "saturday"
            else "easy"
        )
    template = dict(zip(weekdays, template_values))

    return {
        "outline": {
            "duration_weeks": duration_weeks,
            "start_date": start_date,
            "goal_event": "Berlin Marathon",
            "goal_date": "2026-09-27",
            "phases": [
                {
                    "weeks": list(range(1, duration_weeks + 1)),
                    "phase": "Base",
                    "weekly_volume_km": 50,
                    "intensity_distribution": "80/20",
                    "focus": "aerobic foundation",
                }
            ],
            "weekly_template": template,
        },
        "constraints_acknowledged": {
            "max_session_minutes": 90,
            "training_days_per_week": training_days_per_week,
            "available_sports": ["running"],
        },
    }


def _make_executor_sessions(
    *,
    week_start: date,
    template: dict[str, str],
) -> dict:
    """Build a valid executor response for one week."""
    weekdays = ["monday", "tuesday", "wednesday", "thursday",
                "friday", "saturday", "sunday"]
    sessions = []
    for idx, day in enumerate(weekdays):
        slot = template[day]
        if slot == "rest":
            continue
        sessions.append({
            "day": day,
            "date": (week_start + timedelta(days=idx)).isoformat(),
            "sport": "running",
            "name": f"{slot.title()} run",
            "description": "Generated by test",
            "duration_minutes": 45 if slot == "easy" else 60,
            "intensity": "low" if slot == "easy" else "moderate",
        })
    return {"sessions": sessions}


def _mock_completion(content: str) -> MagicMock:
    """Build a chat_completion-shaped MagicMock returning `content`."""
    msg = SimpleNamespace(content=content)
    choice = SimpleNamespace(message=msg)
    resp = SimpleNamespace(choices=[choice])
    return resp


# ---------------------------------------------------------------------------
# Heuristic
# ---------------------------------------------------------------------------

class TestComplexityHeuristic:
    """`should_use_plan_and_execute` threshold and tier gating."""

    def test_free_tier_never_triggers(self):
        request = {"duration_weeks": 16}
        profile = _make_profile(training_days_per_week=6)
        assert should_use_plan_and_execute(request, profile, "free") is False

    def test_pro_short_plan_does_not_trigger(self):
        # 2 weeks * 5 days = 10 sessions, under threshold 14.
        request = {"duration_weeks": 2}
        profile = _make_profile(training_days_per_week=5)
        assert should_use_plan_and_execute(request, profile, "pro") is False

    def test_pro_at_threshold_triggers(self):
        # 3 weeks * 5 days = 15 sessions >= 14.
        request = {"duration_weeks": 3}
        profile = _make_profile(training_days_per_week=5)
        assert should_use_plan_and_execute(request, profile, "pro") is True

    def test_pro_just_below_threshold(self):
        # 2 weeks * 6 days = 12 sessions < 14.
        request = {"duration_weeks": 2}
        profile = _make_profile(training_days_per_week=6)
        assert should_use_plan_and_execute(request, profile, "pro") is False

    def test_pro_just_above_threshold(self):
        # 2 weeks * 7 days = 14, exactly threshold.
        request = {"duration_weeks": 2}
        profile = _make_profile(training_days_per_week=7)
        assert should_use_plan_and_execute(request, profile, "pro") is True

    def test_missing_duration_returns_false(self):
        request: dict = {}
        profile = _make_profile()
        assert should_use_plan_and_execute(request, profile, "pro") is False

    def test_long_plan_capped_at_max(self):
        # 100 weeks should be capped to _MAX_PLAN_WEEKS but heuristic
        # still triggers (capped value is plenty above threshold).
        request = {"duration_weeks": 100}
        profile = _make_profile()
        assert should_use_plan_and_execute(request, profile, "pro") is True


# ---------------------------------------------------------------------------
# Free-tier clamp
# ---------------------------------------------------------------------------

class TestFreeTierClamp:
    def test_clamp_long_request(self):
        out = clamp_for_free_tier({"duration_weeks": 12, "focus": "marathon"})
        assert out["duration_weeks"] == 1
        assert out["_free_tier_clamped_from"] == 12
        # focus preserved
        assert out["focus"] == "marathon"

    def test_clamp_short_request_untouched(self):
        out = clamp_for_free_tier({"duration_weeks": 1})
        assert out == {"duration_weeks": 1}

    def test_clamp_no_duration_untouched(self):
        out = clamp_for_free_tier({"focus": "easy week"})
        assert out == {"focus": "easy week"}

    def test_clamp_returns_new_dict(self):
        original = {"duration_weeks": 8}
        out = clamp_for_free_tier(original)
        assert original == {"duration_weeks": 8}  # not mutated
        assert out is not original


# ---------------------------------------------------------------------------
# Outline validation
# ---------------------------------------------------------------------------

class TestOutlineValidation:
    def test_valid_outline_passes(self):
        payload = _make_outline_payload(duration_weeks=4)
        request = {"duration_weeks": 4}
        profile = _make_profile()
        assert planner_mod._validate_outline(payload, request, profile) is None

    def test_missing_outline_object(self):
        err = planner_mod._validate_outline({}, {}, _make_profile())
        assert "missing 'outline'" in err

    def test_phases_with_gap_rejected(self):
        payload = _make_outline_payload(duration_weeks=4)
        # Drop week 3 from the phases.
        payload["outline"]["phases"][0]["weeks"] = [1, 2, 4]
        err = planner_mod._validate_outline(payload, {}, _make_profile())
        assert err is not None
        assert "weeks" in err

    def test_invalid_weekday_slot_rejected(self):
        payload = _make_outline_payload(duration_weeks=4)
        payload["outline"]["weekly_template"]["monday"] = "blast"
        err = planner_mod._validate_outline(payload, {}, _make_profile())
        assert err is not None and "monday" in err

    def test_training_days_mismatch_rejected(self):
        payload = _make_outline_payload(
            duration_weeks=4, training_days_per_week=5,
        )
        profile = _make_profile(training_days_per_week=6)
        err = planner_mod._validate_outline(payload, {}, profile)
        assert err is not None and "training days" in err

    def test_non_monday_start_date_rejected(self):
        payload = _make_outline_payload(duration_weeks=4)
        # Saturday.
        payload["outline"]["start_date"] = "2026-06-06"
        err = planner_mod._validate_outline(payload, {}, _make_profile())
        assert err is not None and "Monday" in err


# ---------------------------------------------------------------------------
# Executor sanitization
# ---------------------------------------------------------------------------

class TestExecutorSanitization:
    def test_clean_sessions_pass(self):
        outline = _make_outline_payload(duration_weeks=2)["outline"]
        profile = _make_profile()
        slot = planner_mod._build_week_slot(outline, 1, profile)
        week_start = date.fromisoformat(slot["week_start_date"])
        payload = _make_executor_sessions(
            week_start=week_start, template=slot["weekday_template"],
        )
        sanitized, err = planner_mod._sanitize_executor_sessions(
            payload["sessions"], slot, profile,
        )
        assert err is None
        # Should equal the number of non-rest days.
        expected = sum(
            1 for v in slot["weekday_template"].values() if v != "rest"
        )
        assert len(sanitized) == expected

    def test_duration_over_cap_rejected(self):
        outline = _make_outline_payload(duration_weeks=2)["outline"]
        profile = _make_profile(max_session_minutes=60)
        slot = planner_mod._build_week_slot(outline, 1, profile)
        week_start = date.fromisoformat(slot["week_start_date"])
        payload = _make_executor_sessions(
            week_start=week_start, template=slot["weekday_template"],
        )
        # Boost first session over the cap.
        payload["sessions"][0]["duration_minutes"] = 200
        _, err = planner_mod._sanitize_executor_sessions(
            payload["sessions"], slot, profile,
        )
        assert err is not None and "exceeds" in err

    def test_missing_day_rejected(self):
        outline = _make_outline_payload(duration_weeks=2)["outline"]
        profile = _make_profile()
        slot = planner_mod._build_week_slot(outline, 1, profile)
        week_start = date.fromisoformat(slot["week_start_date"])
        payload = _make_executor_sessions(
            week_start=week_start, template=slot["weekday_template"],
        )
        # Drop the first session.
        payload["sessions"] = payload["sessions"][1:]
        _, err = planner_mod._sanitize_executor_sessions(
            payload["sessions"], slot, profile,
        )
        assert err is not None and "missing" in err

    def test_rest_day_session_silently_dropped(self):
        outline = _make_outline_payload(duration_weeks=2)["outline"]
        profile = _make_profile()
        slot = planner_mod._build_week_slot(outline, 1, profile)
        week_start = date.fromisoformat(slot["week_start_date"])
        payload = _make_executor_sessions(
            week_start=week_start, template=slot["weekday_template"],
        )
        # Inject a session for a rest day.
        rest_day = next(
            d for d, v in slot["weekday_template"].items() if v == "rest"
        )
        rest_offset = planner_mod._WEEKDAY_TO_OFFSET[rest_day]
        payload["sessions"].append({
            "day": rest_day,
            "date": (week_start + timedelta(days=rest_offset)).isoformat(),
            "sport": "running",
            "name": "Extra",
            "duration_minutes": 30,
            "intensity": "low",
        })
        sanitized, err = planner_mod._sanitize_executor_sessions(
            payload["sessions"], slot, profile,
        )
        assert err is None
        assert all(s["day"] != rest_day for s in sanitized)

    def test_invalid_sport_replaced_with_available(self):
        outline = _make_outline_payload(duration_weeks=2)["outline"]
        profile = _make_profile(available_sports=["running"])
        slot = planner_mod._build_week_slot(outline, 1, profile)
        week_start = date.fromisoformat(slot["week_start_date"])
        payload = _make_executor_sessions(
            week_start=week_start, template=slot["weekday_template"],
        )
        payload["sessions"][0]["sport"] = "kayaking"
        sanitized, err = planner_mod._sanitize_executor_sessions(
            payload["sessions"], slot, profile,
        )
        assert err is None
        assert sanitized[0]["sport"] == "running"


# ---------------------------------------------------------------------------
# End-to-end happy path (mocked LLM)
# ---------------------------------------------------------------------------

class TestEndToEnd:
    def test_happy_path(self):
        """Full Plan-and-Execute run with mocked planner+executor."""
        profile = _make_profile()
        request = {"duration_weeks": 3, "goal_event": "Berlin Marathon"}
        outline_payload = _make_outline_payload(duration_weeks=3)
        outline = outline_payload["outline"]

        def fake_completion(messages, system_prompt=None, **kwargs):
            # First call uses planner_system.md. Subsequent calls use
            # the executor_system.md. We disambiguate by inspecting the
            # system prompt header.
            if system_prompt and "PLANNER" in system_prompt:
                return _mock_completion(json.dumps(outline_payload))
            # Executor: parse week_index from the user message JSON block.
            user_content = messages[0]["content"]
            week_slot = json.loads(
                user_content.split("```json", 1)[1].split("```", 1)[0]
            )
            week_start = date.fromisoformat(week_slot["week_start_date"])
            return _mock_completion(
                json.dumps(
                    _make_executor_sessions(
                        week_start=week_start,
                        template=week_slot["weekday_template"],
                    )
                )
            )

        with patch.object(planner_mod, "chat_completion", side_effect=fake_completion):
            result = generate_training_plan(request=request, profile=profile)

        assert result.mode == "plan_and_execute"
        plan = result.plan
        assert plan["start_date"] == outline["start_date"]
        assert plan["focus"]
        expected_count = 3 * profile["constraints"]["training_days_per_week"]
        assert len(plan["sessions"]) == expected_count
        # Every session inside the date range.
        sd = date.fromisoformat(plan["start_date"])
        for s in plan["sessions"]:
            d = date.fromisoformat(s["date"])
            assert sd <= d < sd + timedelta(days=3 * 7)
            assert s["duration_minutes"] <= 90
            assert s["sport"] == "running"

    def test_planner_json_parse_failure_falls_back(self):
        profile = _make_profile()
        request = {"duration_weeks": 4}

        def bad_planner(messages, system_prompt=None, **kwargs):
            return _mock_completion("not json at all {{{")

        with patch.object(planner_mod, "chat_completion", side_effect=bad_planner):
            result = generate_training_plan(request=request, profile=profile)

        assert result.mode == "inline_fallback"
        assert "fallback_reason" in result.meta
        # Original request preserved.
        assert result.plan["duration_weeks"] == 4

    def test_executor_invalid_returns_fallback(self):
        profile = _make_profile()
        request = {"duration_weeks": 3}
        outline_payload = _make_outline_payload(duration_weeks=3)

        def fake_completion(messages, system_prompt=None, **kwargs):
            if system_prompt and "PLANNER" in system_prompt:
                return _mock_completion(json.dumps(outline_payload))
            # Always return invalid executor output.
            return _mock_completion('{"sessions": []}')

        with patch.object(planner_mod, "chat_completion", side_effect=fake_completion):
            result = generate_training_plan(request=request, profile=profile)

        assert result.mode == "inline_fallback"
        assert "executor" in result.meta.get("fallback_reason", "")


# ---------------------------------------------------------------------------
# Validation against athlete constraints (post-assembly)
# ---------------------------------------------------------------------------

class TestConstraintValidation:
    def test_valid_plan_no_errors(self):
        profile = _make_profile()
        outline_payload = _make_outline_payload(duration_weeks=2)
        outline = outline_payload["outline"]
        # Build sessions matching the outline.
        sd = date.fromisoformat(outline["start_date"])
        all_sessions = []
        for wk in range(2):
            week_start = sd + timedelta(days=wk * 7)
            all_sessions.extend(
                _make_executor_sessions(
                    week_start=week_start,
                    template=outline["weekly_template"],
                )["sessions"]
            )
        plan = {
            "start_date": outline["start_date"],
            "sessions": all_sessions,
        }
        errors = planner_mod._validate_against_constraints(plan, profile, outline)
        assert errors == []

    def test_session_over_cap_flagged(self):
        profile = _make_profile(max_session_minutes=60)
        outline = _make_outline_payload(duration_weeks=1)["outline"]
        sd = date.fromisoformat(outline["start_date"])
        sessions = _make_executor_sessions(
            week_start=sd, template=outline["weekly_template"],
        )["sessions"]
        sessions[0]["duration_minutes"] = 200
        plan = {"start_date": outline["start_date"], "sessions": sessions}
        errors = planner_mod._validate_against_constraints(plan, profile, outline)
        assert any("exceeds" in e for e in errors)

    def test_wrong_session_count_per_week_flagged(self):
        profile = _make_profile(training_days_per_week=5)
        outline = _make_outline_payload(
            duration_weeks=1, training_days_per_week=5,
        )["outline"]
        sd = date.fromisoformat(outline["start_date"])
        sessions = _make_executor_sessions(
            week_start=sd, template=outline["weekly_template"],
        )["sessions"]
        # Drop one.
        sessions = sessions[:-1]
        plan = {"start_date": outline["start_date"], "sessions": sessions}
        errors = planner_mod._validate_against_constraints(plan, profile, outline)
        assert any("week 1" in e and "expected 5" in e for e in errors)


# ---------------------------------------------------------------------------
# save_plan integration (heuristic flows)
# ---------------------------------------------------------------------------

class TestSavePlanIntegration:
    """Verify the heuristic plumbing inside save_plan without hitting LLMs."""

    def _make_user_model(self, *, tier: str = "free"):
        um = MagicMock()
        um.user_id = "test-uid"
        um.project_profile.return_value = _make_profile(tier=tier)
        return um

    def _register(self, user_model):
        from src.agent.tools.registry import ToolRegistry
        registry = ToolRegistry()
        # Disable supabase persistence: use the file-backed fallback path
        # so we do not touch the DB during unit tests.
        with patch("src.agent.tools.planning_tools.get_settings") as mock_get:
            settings = MagicMock()
            settings.use_supabase = False
            settings.agenticsports_user_id = "test-uid"
            mock_get.return_value = settings
            from src.agent.tools.planning_tools import register_planning_tools
            register_planning_tools(registry, user_model)
        return registry

    def test_free_tier_long_plan_clamped(self, tmp_path, monkeypatch):
        """Free-tier user passing 12 weeks gets clamped to 1 week, NO planner."""
        monkeypatch.chdir(tmp_path)
        user_model = self._make_user_model(tier="free")
        registry = self._register(user_model)
        save_tool = registry._tools["save_plan"]

        with patch("src.agent.planner.generate_training_plan") as mock_gen:
            result = save_tool.handler(plan={
                "duration_weeks": 12,
                "start_date": _next_monday().isoformat(),
                "sessions": [],
            })
            mock_gen.assert_not_called()

        assert result["saved"] is True

    def test_pro_tier_short_plan_skips_planner(self, tmp_path, monkeypatch):
        """Pro tier but session_count<14: planner is NOT invoked."""
        monkeypatch.chdir(tmp_path)
        user_model = self._make_user_model(tier="pro")
        registry = self._register(user_model)
        save_tool = registry._tools["save_plan"]

        with patch("src.agent.planner.generate_training_plan") as mock_gen:
            result = save_tool.handler(plan={
                "duration_weeks": 2,
                "start_date": _next_monday().isoformat(),
                "sessions": [{
                    "day": "monday",
                    "date": _next_monday().isoformat(),
                    "sport": "running",
                    "name": "Easy",
                    "duration_minutes": 45,
                    "intensity": "low",
                }],
            })
            mock_gen.assert_not_called()

        assert result["saved"] is True

    def test_pro_tier_long_plan_triggers_planner(self, tmp_path, monkeypatch):
        """Pro tier, duration_weeks=12: planner IS invoked."""
        monkeypatch.chdir(tmp_path)
        user_model = self._make_user_model(tier="pro")
        registry = self._register(user_model)
        save_tool = registry._tools["save_plan"]

        outline_payload = _make_outline_payload(duration_weeks=3)
        sd = date.fromisoformat(outline_payload["outline"]["start_date"])
        sessions = []
        for wk in range(3):
            week_start = sd + timedelta(days=wk * 7)
            sessions.extend(
                _make_executor_sessions(
                    week_start=week_start,
                    template=outline_payload["outline"]["weekly_template"],
                )["sessions"]
            )
        fake_result = PlannerResult(
            plan={
                "start_date": outline_payload["outline"]["start_date"],
                "focus": "test plan",
                "sessions": sessions,
            },
            mode="plan_and_execute",
            meta={"weeks": 3},
        )

        with patch(
            "src.agent.planner.generate_training_plan",
            return_value=fake_result,
        ) as mock_gen:
            result = save_tool.handler(plan={"duration_weeks": 12})

            mock_gen.assert_called_once()
            args, kwargs = mock_gen.call_args
            assert kwargs["request"]["duration_weeks"] == 12

        assert result["saved"] is True
