"""LLM-judge validation: score plans / sessions against a coaching rubric.

A second Claude instance acts as an independent judge - it does not see
the conversation that produced the plan, only the plan + athlete
context. Returns a numeric score per criterion plus an overall verdict.

Use this after the agent ships a new plan to confirm quality, or as
part of a regression sweep when you change prompts / tools.
"""

from __future__ import annotations

import json
import logging
import os
import sys

import click

from athctl.common import EXIT_BACKEND_DOWN, console, emit, get_supabase, require_active_user

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Rubric
# ---------------------------------------------------------------------------

RUBRIC = {
    "progressive_overload": (
        "Does the plan show progressive overload appropriate for the phase? "
        "Volume and intensity should rise over weeks (base building) or "
        "feature targeted overreaching followed by recovery (build/peak)."
    ),
    "recovery_balance": (
        "Is recovery integrated? At least 1-2 easy or rest days per week, "
        "no two hard days back-to-back, and a deload every 3-4 weeks."
    ),
    "goal_specificity": (
        "Does the plan move the athlete towards the stated goal "
        "(event, target time, race pace)? Race-specific work in build/peak."
    ),
    "plausible_targets": (
        "Are pace / HR / power targets plausible for the athlete's current "
        "fitness and the phase? Easy paces should match aerobic effort, "
        "threshold should sit at LT, race pace only in build/peak."
    ),
    "constraint_compliance": (
        "Does the plan respect athlete constraints (training days/week, "
        "max session minutes, sport preferences, free-form notes)?"
    ),
    "session_variety": (
        "Mix of session types appropriate to the goal: easy, tempo, "
        "threshold, intervals, long, strength, cross-train. Avoid monotony."
    ),
}


JUDGE_SYSTEM_PROMPT = """\
You are an independent endurance-coaching judge evaluating a training plan
generated by another coach for a specific athlete. Score the plan honestly
against the rubric. Each criterion is scored 0-100. Be specific in feedback:
cite which session or week supports each score. Be tough but constructive -
this is regression-testing the coach, not advising the athlete.

Return ONLY a JSON object with this exact schema:

{
  "scores": {
    "<criterion_name>": {"score": int (0-100), "feedback": "..." },
    ...
  },
  "overall_score": int (weighted average, weights below),
  "verdict": "pass" | "fail" | "mixed",
  "key_issues": ["...", ...],
  "key_strengths": ["...", ...]
}

Weights for overall:
- progressive_overload 20
- recovery_balance 20
- goal_specificity 20
- plausible_targets 15
- constraint_compliance 15
- session_variety 10

Verdict: "pass" if overall >= 75, "fail" if < 60, else "mixed".
"""


def _call_judge(plan_json: dict, athlete_context: dict) -> dict:
    """Run the judge LLM call and return its JSON verdict.

    Uses anthropic SDK directly (separate API call from the main coach).
    Falls back gracefully when the SDK is unavailable.
    """
    try:
        import anthropic
    except ImportError:
        return {"error": "anthropic SDK not installed (uv add anthropic)"}

    rubric_json = json.dumps(RUBRIC, indent=2)
    user_msg = (
        "## Athlete Context\n"
        f"```json\n{json.dumps(athlete_context, indent=2, default=str)}\n```\n\n"
        "## Plan to Evaluate\n"
        f"```json\n{json.dumps(plan_json, indent=2, default=str)}\n```\n\n"
        "## Rubric\n"
        f"```json\n{rubric_json}\n```\n\n"
        "Now produce your JSON verdict."
    )

    try:
        client = anthropic.Anthropic()
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=4096,
            system=JUDGE_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_msg}],
        )
    except Exception as exc:
        return {"error": f"Judge LLM call failed: {exc}"}

    text = ""
    for block in response.content:
        if getattr(block, "type", None) == "text":
            text += getattr(block, "text", "")

    text = text.strip()
    # Strip code fences if model wrapped JSON
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text
        text = text.rsplit("```", 1)[0]
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        return {"error": f"Could not parse judge response as JSON: {exc}", "raw": text[:2000]}


def _athlete_context(uid: str) -> dict:
    """Build a minimal athlete context dict for the judge."""
    client = get_supabase()
    profile = client.table("profiles").select("*").eq("user_id", uid).execute()
    beliefs = (
        client.table("beliefs")
        .select("text, category, confidence")
        .eq("user_id", uid)
        .eq("active", True)
        .order("confidence", desc=True)
        .limit(15)
        .execute()
    )
    return {
        "profile": profile.data[0] if profile.data else {},
        "beliefs": beliefs.data or [],
    }


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@click.group(help="LLM-judge validation against a coaching rubric.")
def validate() -> None:
    """Validate plans / sessions via an independent judge."""


@validate.command("plan", help="Validate a specific saved plan (or the active one).")
@click.option("--id", "plan_id", default=None, help="Plan id; default is the active plan.")
def validate_plan(plan_id: str | None) -> None:
    uid = require_active_user()
    client = get_supabase()

    if not plan_id:
        res = (
            client.table("plans")
            .select("id, plan_data")
            .eq("user_id", uid)
            .eq("active", True)
            .limit(1)
            .execute()
        )
        if not res.data:
            print("No active plan and no --id given.", file=sys.stderr)
            sys.exit(2)
        plan_id = res.data[0]["id"]
        plan_data = res.data[0]["plan_data"]
    else:
        res = client.table("plans").select("plan_data").eq("id", plan_id).execute()
        if not res.data:
            print(f"Plan {plan_id} not found.", file=sys.stderr)
            sys.exit(2)
        plan_data = res.data[0]["plan_data"]

    emit(f"Judging plan {plan_id}...")
    verdict = _call_judge(plan_data, _athlete_context(uid))

    if "error" in verdict:
        console.print(f"[red]Judge error:[/red] {verdict['error']}")
        sys.exit(EXIT_BACKEND_DOWN)

    overall = verdict.get("overall_score")
    v = verdict.get("verdict")
    emit(
        f"Verdict: {v} (overall {overall}/100)",
        data={"plan_id": plan_id, "verdict": verdict},
    )

    scores = verdict.get("scores", {})
    for crit, payload in scores.items():
        score = payload.get("score") if isinstance(payload, dict) else None
        feedback = payload.get("feedback") if isinstance(payload, dict) else ""
        console.print(f"  [bold]{crit}[/bold]: {score}/100 - {str(feedback)[:160]}")

    issues = verdict.get("key_issues") or []
    if issues:
        console.print("\n[red]Key issues:[/red]")
        for i in issues:
            console.print(f"  - {i}")
    strengths = verdict.get("key_strengths") or []
    if strengths:
        console.print("\n[green]Key strengths:[/green]")
        for s in strengths:
            console.print(f"  - {s}")


@validate.command("batch", help="Run the judge against N independent plan generations.")
@click.option("--runs", type=int, default=3, help="How many times to re-judge.")
@click.option("--id", "plan_id", default=None, help="Plan id; default active.")
def validate_batch(runs: int, plan_id: str | None) -> None:
    """Re-judge the same plan multiple times to see judge consistency."""
    uid = require_active_user()
    client = get_supabase()

    if not plan_id:
        res = (
            client.table("plans")
            .select("id, plan_data")
            .eq("user_id", uid)
            .eq("active", True)
            .limit(1)
            .execute()
        )
        if not res.data:
            print("No active plan and no --id given.", file=sys.stderr)
            sys.exit(2)
        plan_id = res.data[0]["id"]
        plan_data = res.data[0]["plan_data"]
    else:
        res = client.table("plans").select("plan_data").eq("id", plan_id).execute()
        plan_data = res.data[0]["plan_data"]

    ctx = _athlete_context(uid)
    scores: list[int] = []
    for i in range(max(1, runs)):
        verdict = _call_judge(plan_data, ctx)
        if "error" in verdict:
            console.print(f"[red]Run {i+1} failed:[/red] {verdict['error']}")
            continue
        s = verdict.get("overall_score")
        if isinstance(s, int):
            scores.append(s)
        console.print(f"Run {i+1}: {verdict.get('verdict')} ({s}/100)")

    if scores:
        avg = sum(scores) / len(scores)
        spread = max(scores) - min(scores)
        emit(
            f"\nMean overall: {avg:.1f}/100, spread {spread}",
            data={"plan_id": plan_id, "scores": scores, "mean": avg, "spread": spread},
        )
